apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-backend-config
  namespace: production # Namespace tempat API berjalan
data:
  # --- Network Config ---
  DOMAIN: "localhost"
  FRONTEND_HOST: "http://localhost:5173"
  ENVIRONMENT: "production"

  # --- App Config ---
  PROJECT_NAME: "Full Stack FastAPI Project"
  STACK_NAME: "full-stack-fastapi-project"
  BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173"

  # --- Email Config ---
  SMTP_HOST: ""
  EMAILS_FROM_EMAIL: "info@example.com"
  SMTP_TLS: "True"
  SMTP_SSL: "False"
  SMTP_PORT: "587"

  # --- DATABASE CONNECTION (PENTING) ---
  # Format: <nama-service>.<namespace-db>
  POSTGRES_SERVER: "postgresql-prod.database-prod.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "fastapi" # Pastikan nama DB 'app' sudah dibuat di postgresql-test
