apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: testing
  labels:
    app: fastapi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
        - name: backend
          image: diwamln/fastapi-backend:build-8-4b77302-test
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8000

          # Load ENV dari ConfigMap & Secret
          envFrom:
            - configMapRef:
                name: testing-fastapi-backend-config
            - secretRef:
                name: testing-fastapi-backend-secrets

          # =========================
          # PROBES (FASTAPI SAFE)
          # =========================

          # Startup probe → kasih waktu FastAPI + DB + config init
          startupProbe:
            tcpSocket:
              port: 8000
            failureThreshold: 30   # 30 x 5s = 150s max startup
            periodSeconds: 5

          # Liveness → cek process hidup, JANGAN endpoint berat
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          # Readiness → cek API sudah siap terima traffic
          readinessProbe:
            httpGet:
              path: /api/v1/utils/health-check
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3

          # =========================
          # RESOURCES
          # =========================
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
